### ISSUE TITLE
[Quest] The Arts of a Rogue (26207)

### ISSUE THREAD

**Issue by curicius** [revui/Legion_7.3.5-Project-Info#386]
Unable to finish The Arts of a Rogue quest. Using Eviscerate on dummies is not counted properly. Additionally reward for this quest is the same as reward for previous quest - The Future of Gnomeregan (26206). 

![WoWScrnShot_020620_205708](https://user-images.githubusercontent.com/60756043/73974622-fd90d880-4924-11ea-9dbc-6ac66fcd55d3.jpg)
![WoWScrnShot_020620_205623](https://user-images.githubusercontent.com/60756043/73974634-01245f80-4925-11ea-93ed-569663c57ee6.jpg)

https://www.wowhead.com/quest=26207/the-arts-of-a-rogue
https://www.wowhead.com/quest=26206/the-future-of-gnomeregan

**Comment by revui** [comment]
At the starting zones, the classes are not have any partice quests in 7.3.5. These quests are echoes from my 4.x Cataclysm DataBase, and I'm not removed them yet (with this patch, almost every Pratice quests for classes are broken since they referring on different ability ids).

They will removed soon from all starting zones
